server:
  port: 8181
  servlet:
    context-path: /sa

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/sample-admin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
      #连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      #连接超时时间
      max-wait: 30000
      #配置监测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000

  # redis配置
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    #连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2

privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC9MGsBqtXGcGuC
  zh4fMQ6IN4yZZXnDFsrWrqKsNqixvPhvWEEqtrwcpZ91cDKFwG4gIr4Tgk2kBYVh
  c9guze7jSFojMksEjBesXj/1jq8LQ4QczoLw0ebeFB96olghNPmHt+HEuA1XFBsT
  hPG5uBqkBEmzCDp9yajXsx9qqQhtNuT6RRyaM7i+mEZ1MDwKK9pzZf9uE1ToPaNK
  VMaqK3gt8l2xvDFfNlVc28cCLg/J51QU1UY14mshOKGJDFpGdyNyJzsn71m1BZVG
  X/IKiy61idsqGcmOjvRizshEupJ3hJOz6eptR9nFoeolmVZ7asgjCAy+f/7ovlmz
  YE6wMZrjAgMBAAECggEBAJl9GLOnl/yA5JihBQslT7bv6l/hViIS8cmusUeqqL5a
  o+wh2+z9iCxtqqsqtbKR5kaoKTHGu5rg58+inreKV8+JuadofDhaODKd3KIqepVW
  125PlSgwA3AVP1zNLVbzlaaoZsCk2h3VsAnsB/k3BlYfLHPVry6yVwt4xXpRXQbM
  5teUiUI8RLqrNhsnu03q8vNJkrarLx5oJHVtspKqYoAUWX+SL7/LC5tDCsd6WEy+
  2rDqzpHf4ymGy785tPBt540Kiwzrwk/p3/UM1abtyalOmbMTqwSCDaaJhEbGkP7t
  Q0qyRttpk9VFbDgWjjKVpVEGUXUZhj/0lPztmNhIH3ECgYEA6PuZWiZDVOLrRZMK
  m4R+cT12tMS6d/l9S3Zf6ENPZIFnjjc29c3Eh5nqwECjZan5Etu+nMyqfMGRRm6I
  oUK2hmdboeoCCh/PG1cuF4DRBV+0fvXnodkLCidITMQrHbGzUzEzOYz0+FxRXDgq
  B6n5t1y+IhObSOW0yEn9qPNpnHcCgYEAz+E6GUJPl5o7661vmTv9xkdQPckk6baC
  ULurka6Q3WtRTiBDxlHPHcziufVVUXhrjnFneZP7GL8ItqkhQqhuj4cGYGbPVoSG
  JEaMttLHeeja8L/9gp7GYH/DjvFWP5ni68pg3YyJFDPursapqUWmrtlbXOycJXJj
  iCQM2Yj4S/UCgYBsLn+ro366SM/UM43GXsRTkqWvFHY9RUTPqHyqHa8czRWnrK3B
  fzVVfbvKX3k/uKgmAJFGv6YeXcc2PBcHQjH8wLuEuGMQDmsdl+KYGUF1TFZEaayP
  s3dz1H+23ZPjquLIq1zMyU3qkPtaZd3mRx/j65WBvzbop3jFU84MCFKuywKBgQC7
  DYQ01FlAJjWC1RYVQUkSEHtgjU0cy/Ao6yXvua96vaV0ck3p9xUyUHk3MU2rOHs3
  uk2MtZ583vDdRAS8sUiC99HCDuDEjg0SOTVHERUTWncfqPJZhbsle/Gg/wJHypXI
  69sLn/h86Fn+hJ6HxTe+H7E5RWMfwvVSvHWfjMM3vQKBgHnujhaVO04dYpeNZhYO
  uC8lMJkwoDkQ2QLgbKdFBXKHdIBYkdP0aTVBU8uQIYFusdHoZZR7LiZbjsHHxG3m
  PcQBu8LuCnBoVZzRXpSJmbl8v2EMQV9qBJPrcNccqMf8U0Giotxm1x32Odak4vJp
  KoWUMqaAQ7RO05TCYKGTd7gb
publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvTBrAarVxnBrgs4eHzEO
  iDeMmWV5wxbK1q6irDaosbz4b1hBKra8HKWfdXAyhcBuICK+E4JNpAWFYXPYLs3u
  40haIzJLBIwXrF4/9Y6vC0OEHM6C8NHm3hQfeqJYITT5h7fhxLgNVxQbE4Txubga
  pARJswg6fcmo17MfaqkIbTbk+kUcmjO4vphGdTA8Civac2X/bhNU6D2jSlTGqit4
  LfJdsbwxXzZVXNvHAi4PyedUFNVGNeJrITihiQxaRncjcic7J+9ZtQWVRl/yCosu
  tYnbKhnJjo70Ys7IRLqSd4STs+nqbUfZxaHqJZlWe2rIIwgMvn/+6L5Zs2BOsDGa
  4wIDAQAB
